language: android

android:
  components:
  - tools
  - platform-tools

jdk:
- oraclejdk8

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

script: "./gradlew runUnitTests --no-daemon"