language: android

android:
  components:
  - tools
  - platform-tools
  - android-28
  - build-tools-28.0.3
  - extra-android-m2repository
  - extra-google-m2repository
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"

jdk:
- oraclejdk8

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

script: "./gradlew runUnitTests --no-daemon"