@startuml
hide empty members
interface CacheDelegate<DATA, PARAMS> {
        +get(params: PARAMS): Entity<D>?
        +save(params: PARAMS, entity: Entity<DATA>)
        +invalidate(params: PARAMS)
        +invalidateAll()
        +delete(params: PARAMS)
}
@enduml